### ISSUE TITLE
Primer problema ficticio

### ISSUE THREAD

**Issue by erikmartinjordan** [erikmartinjordan/queponemos#1]
Esto es un comentario de prueba para familiarizarse con GitHub; podemos abrir y cerrar hilos según ideas o problemas que vaya surgiendo.

Cada sugerencia o comentario debería ser una _issue_ que hay que cerrar.

Si habéis llegado aquí abajo, manifestaos, pinches pendejos. 😄

**Comment by wernerschiller** [comment]
Por medio de la presente, manifiesto: oleee!

**Comment by Vit020490** [comment]
Vicente approves
